import React from 'react';
import { createRoot } from 'react-dom/client';
import singleSpaReact from 'single-spa-react';
import App from './App';
import type { CustomProps } from './types';

/**
 * §9.1 single-spa lifecycle export. Any single-spa host can mount this via
 * mountRootParcel(fluidAppParcel, customProps) — §3.1's example passes
 * `domElement: containerRef.current`, so domElementGetter must honor a
 * host-supplied container explicitly rather than relying on single-spa-react's
 * name-based default (which would create its own detached div instead).
 *
 * Standalone mode (§3.2) reuses this same bundle: the dev/prod HTML harness
 * generated by webpack-config-single-spa-react bootstraps/mounts it directly
 * with no custom taskCode prop, so App.tsx's resolveTaskContextPointer falls
 * back to parsing the URL instead of reading customProps.
 *
 * NOTE: single-spa-react's published API (React/ReactDOMClient/rootComponent)
 * is the version actually on npm as of this writing — verified against the
 * installed package's .d.ts, not assumed from docs, since some docs sources
 * describe a newer createElement/renderReactNode shape not yet released.
 */
function domElementGetter(props: CustomProps): HTMLElement {
  if (props.domElement) return props.domElement;
  let el = document.getElementById('app');
  if (!el) {
    el = document.createElement('div');
    el.id = 'app';
    document.body.appendChild(el);
  }
  return el;
}

export const { bootstrap, mount, unmount } = singleSpaReact({
  React,
  ReactDOMClient: { createRoot },
  rootComponent: App,
  domElementGetter,
  errorBoundary(err) {
    console.error('[transapp] uncaught render error:', err);
    return <div className="fluid-app-error">Something went wrong loading this task.</div>;
  },
});
